name: Java CI for checkneighbors

on:
  push:
    paths:
      - 'dependency-management/checkneighbours/**'
  pull_request:
    paths:
      - 'dependency-management/checkneighbours/**'

defaults:
  run:
    working-directory: dependency_management/checkneighbors

jobs:
  test:
    runs-on: ubuntu-latest

  steps:
  - name: Checkout repositoy
    uses: actions/checkout@v4

  - name: Set up to JDK 21
    uses: actions/setup-java@v4
    with:
      java-version: '17'
      distribution: 'temurin'

  - name: Gran execute permissins for gradlew
    run: chmod +x dependency-management/checkneighbours/gradlew

  - name: Run tests with gradle
    run:
      cd dependency-management/checkneighbours
      ./gradlew test
