name: Java CI for checkneighbors

on:
  push:
    paths:
      - 'dependency-management/checkneighbours/**'
  pull_request:
    paths:
      - 'dependency-management/checkneighbours/**'

defaults:
  run:
    working-directory: dependency_management/checkneighbors

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permissions for gradlew
      run: chmod +x

    - name: Run tests with gradle
      run: ./gradlew test
