name: Java CI for checkneighbors

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: List directory structure
      run: find . -type d | grep -i "check\|depend" || echo "No matching directories found"

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Find Gradle wrapper
      run: find . -name "gradlew" -type f || echo "No gradlew found"
      
    - name: Grant execute permissions for gradlew
      run: chmod +x ./dependency-management/checkneighbours/gradlew || echo "Failed to set permissions - file may not exist"

    - name: Run tests with gradle
      working-directory: ./dependency-management/checkneighbours
      run: ./gradlew test || echo "Failed to run tests"
